pod 'AFNetworking', '~>2.0'
pod 'hpple', git: 'https://github.com/jflinter/hpple.git'
pod 'Reveal-iOS-SDK'
pod 'OvershareKit', :podspec => '.'
pod 'Mantle', git: 'https://github.com/jflinter/Mantle'
pod 'MagicalRecord'
pod 'MCSwipeTableViewCell'
pod 'NTDCoreDataTableViewController'
pod 'MFPPorterStemmer', :podspec => '.'
pod 'BayesianKit', git: 'https://github.com/jflinter/BayesianKit'