pod 'AFNetworking', '~>2.0'
pod 'BDDRScrollViewAdditions', '~>1.1'
pod 'TMCache', '~>1.2'
pod 'hpple', git: 'https://github.com/jflinter/hpple.git'
pod 'Reveal-iOS-SDK'
pod 'OvershareKit', :podspec => '.'